/**
 * Socket.io path — kept distinct from the REST surface so a reverse proxy can
 * route WebSocket upgrades independently. The frontend must connect with the
 * same `path`.
 */
export const SOCKET_PATH = '/realtime';

/**
 * Server → client event names. Keeping them centralized means the gateway, the
 * publisher service and the frontend share a single source of truth instead of
 * trading raw strings.
 */
export const ServerEvent = {
	/** Presence roster changed (a user came online / went offline). */
	PRESENCE_UPDATE: 'presence:update',
	/** Someone started/stopped typing in a room. */
	TYPING: 'activity:typing',
	/** Someone is viewing a resource. */
	VIEWING: 'activity:viewing',
	/** A user-directed notification. */
	NOTIFICATION: 'notification',
	/** Something in a channel changed; payload is app-defined. */
	CHANNEL_UPDATE: 'channel:update'
} as const;

/**
 * Client → server event names.
 */
export const ClientEvent = {
	JOIN_ROOM: 'room:join',
	LEAVE_ROOM: 'room:leave',
	TYPING: 'activity:typing',
	VIEWING: 'activity:viewing'
} as const;

/** Every socket of a single user joins this room, so we can target the user. */
export const userRoom = (userId: string) => `user:${userId}`;

/** Firehose room — clients here see every broadcast on the default channel. */
export const FEED_ROOM = 'feed';

/** Room scoped to one resource; comments, typing and viewing land here. */
export const channelRoom = (channelId: string) => `channel:${channelId}`;

/** cuid-shaped ids, as generated by Prisma's `@default(cuid())`. */
const CHANNEL_ROOM_PATTERN = /^channel:[A-Za-z0-9_-]{1,64}$/;

/**
 * Rooms a client may join via the generic `room:join` message.
 *
 * This is an allowlist on purpose. Rooms are plain strings, so an open
 * `socket.join(body.room)` would let any authenticated user join `user:<id>`
 * and receive another user's private notifications (see
 * `RealtimeService.notifyUser`). That is reachable only through this door, so
 * widen the allowlist deliberately — never by passing the client's string
 * straight to `socket.join`.
 */
export const isJoinableRoom = (room: string): boolean =>
	room === FEED_ROOM || CHANNEL_ROOM_PATTERN.test(room);

/** Redis key holding the set of currently-connected user ids (presence). */
export const PRESENCE_KEY = 'realtime:presence:online';
/**
 * Per-user connection counter. A user may have several tabs/devices; they only
 * count as "offline" once every socket has disconnected.
 */
export const presenceCountKey = (userId: string) =>
	`realtime:presence:count:${userId}`;
