/**
 * Bring a generated project up to the current templates.
 *
 * The same three-way merge as `stack add`, across versions instead of
 * features: A is the template as the project's recorded release generated it
 * (that release's own CLI and templates, so its generator's behaviour is
 * reproduced too), B is the current template, both with the project's name,
 * scope, port and features, both formatted with the project's Prettier. A → B
 * is everything the templates changed since, merged into the project.
 *
 * The old release comes from this checkout's git history when there is one
 * (the exact commit if `stack.json` recorded it, else the release tag), or
 * from the npm registry, so upgrade also works from an installed copy.
 */
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';

import { generate } from './generate.mjs';
import { resolveFeatures } from './manifest.mjs';
import { readText, writeText, rmrf } from './fsx.mjs';
import { selection, assertClean, formatLike, mergeTrees } from './add.mjs';

const PACKAGE = '@aurostack/stacks';

function run(cmd, args, opts = {}) {
	return spawnSync(cmd, args, { encoding: 'utf8', ...opts });
}

/**
 * The commit a checkout's templates and CLI are at, or null when there is no
 * checkout or they have uncommitted changes (then no commit describes them).
 */
export function sourceCommit(root) {
	if (!fs.existsSync(path.join(root, '.git'))) return null;
	const head = run('git', ['rev-parse', 'HEAD'], { cwd: root });
	if (head.status !== 0) return null;
	const dirty = run('git', ['status', '--porcelain', '--', 'templates', 'cli'], { cwd: root });
	if (dirty.status !== 0 || dirty.stdout.trim()) return null;
	return head.stdout.trim();
}

/** Unpack the release a project was generated from into `dir`; returns how. */
function fetchRelease(root, stack, dir) {
	fs.mkdirSync(dir, { recursive: true });
	if (fs.existsSync(path.join(root, '.git'))) {
		for (const ref of [stack.stackCommit, `v${stack.stackVersion}`].filter(Boolean)) {
			if (run('git', ['rev-parse', '--verify', '--quiet', `${ref}^{commit}`], { cwd: root }).status !== 0) {
				continue;
			}
			const archive = run('sh', ['-c', `git archive ${ref} cli templates package.json | tar -x -C "${dir}"`], {
				cwd: root
			});
			if (archive.status === 0) return `git ${ref.length === 40 ? ref.slice(0, 7) : ref}`;
		}
	}
	const packed = run('npm', ['pack', `${PACKAGE}@${stack.stackVersion}`, '--pack-destination', dir, '--silent'], {
		cwd: dir
	});
	const tarball = packed.stdout.trim().split('\n').pop();
	if (packed.status !== 0 || !tarball) {
		throw new Error(
			`Could not get stacks ${stack.stackVersion} (the release ${stack.template} was generated from) ` +
				`from git or npm: ${packed.stderr.trim() || 'no tarball'}`
		);
	}
	const untar = run('tar', ['-xzf', tarball, '--strip-components=1', '-C', dir], { cwd: dir });
	if (untar.status !== 0) throw new Error(`Could not unpack ${tarball}: ${untar.stderr}`);
	return `npm ${PACKAGE}@${stack.stackVersion}`;
}

export function upgradeProject(manifest, project, options) {
	const { root, toolVersion, dryRun = false, force = false, exclude = [] } = options;

	const stackFile = path.join(project, 'stack.json');
	if (!fs.existsSync(stackFile)) {
		throw new Error(`${project} has no stack.json: it was not generated by stack, so there is nothing to upgrade from.`);
	}
	const stack = JSON.parse(readText(stackFile));
	if (stack.template !== manifest.name) {
		throw new Error(`${project} was generated from "${stack.template}", not "${manifest.name}".`);
	}
	if (!stack.stackVersion) throw new Error(`${project}/stack.json records no stackVersion to upgrade from.`);

	if (!dryRun && !force) assertClean(project);

	const report = {
		from: stack.stackVersion,
		to: toolVersion,
		source: null,
		dropped: [],
		arrived: [],
		formatted: false,
		written: [],
		merged: [],
		conflicts: [],
		removed: [],
		kept: [],
		envKeys: [],
		excluded: []
	};

	const scratch = fs.mkdtempSync(path.join(os.tmpdir(), 'stack-upgrade-'));
	try {
		const release = path.join(scratch, 'release');
		report.source = fetchRelease(root, stack, release);
		const oldManifest = JSON.parse(readText(path.join(release, 'templates', stack.template, 'template.json')));

		// A: the old release's CLI, with the project's features as that release knew them.
		const oldKnown = Object.keys(oldManifest.features ?? {});
		const oldWith = stack.features.filter((f) => oldKnown.includes(f));
		const oldWithout = oldKnown.filter((f) => !stack.features.includes(f) && !oldManifest.features[f].core);
		const dirA = path.join(scratch, 'before');
		const args = [
			path.join(release, 'cli', 'stack.mjs'),
			'new',
			stack.template,
			dirA,
			'--name',
			stack.name,
			'--no-hooks'
		];
		if (stack.scope) args.push('--scope', stack.scope);
		if (stack.port) args.push('--port', String(stack.port));
		if (stack.description) args.push('--description', stack.description);
		if (oldWith.length) args.push('--with', oldWith.join(','));
		if (oldWithout.length) args.push('--without', oldWithout.join(','));
		const old = run(process.execPath, args);
		if (old.status !== 0) throw new Error(`stacks ${stack.stackVersion} could not regenerate the project: ${old.stderr || old.stdout}`);

		// B: today's template, same features (requirements resolved the same way).
		const { after } = selection(manifest, stack.features, []);
		const enabledB = resolveFeatures(manifest, after);
		const known = Object.keys(manifest.features);
		report.dropped = stack.features.filter((f) => !known.includes(f));
		report.arrived = [...enabledB].filter((f) => !stack.features.includes(f)).sort();
		const dirB = path.join(scratch, 'after');
		generate(manifest, dirB, {
			name: stack.name,
			scope: stack.scope,
			description: stack.description,
			port: stack.port,
			author: stack.author,
			toolVersion,
			...after
		});

		report.formatted = formatLike(project, dirA) && formatLike(project, dirB);
		Object.assign(
			report,
			mergeTrees(project, dirA, dirB, { dryRun, exclude, label: `stacks ${toolVersion}` })
		);

		if (!dryRun) {
			const commit = sourceCommit(root);
			const next = {
				...stack,
				templateVersion: manifest.version || stack.templateVersion,
				stackVersion: toolVersion,
				updatedAt: new Date().toISOString(),
				features: [...enabledB].sort()
			};
			if (commit) next.stackCommit = commit;
			else delete next.stackCommit;
			// An excluded path means the project does not fully match the new
			// release; say so rather than claim it does.
			if (report.excluded.length) next.upgradeExcluded = exclude;
			else delete next.upgradeExcluded;
			writeText(stackFile, JSON.stringify(next, null, '\t') + '\n');
		}
	} finally {
		rmrf(scratch);
	}
	return report;
}
